
let ActionTypes = {
	LOAD_NEWS_CLOUD : 'LOAD_NEWS_CLOUD',
	LOAD_CURRENT_USER_INFO: 'LOAD_CURRENT_USER_INFO',
	AUTH_LOGED_IN: 'AUTH_LOGED_IN',
	AUTH_SIGNED_OUT: 'AUTH_SIGNED_OUT',	
	AUTH_SET_FETCH_TOKEN_STATE: 'AUTH_SET_FETCH_TOKEN_STATE',
	AUTH_SET_IS_TOKEN_FETCH_SUCCESSFULL: 'AUTH_SET_IS_FETCHING_TOKEN_SUCCESSFULL',
	AUTH_SET_USER: 'AUTH_SET_USER'
}

export default ActionTypes;